# PAMS 配置文件示例
# 复制此文件为 config.yaml 并根据需要修改

# 数据库配置
database:
  # 数据库类型: sqlite, postgresql, mysql
  type: "sqlite"
  # SQLite数据库文件路径 (仅当type为sqlite时使用)
  sqlite_path: "pams.db"
  # PostgreSQL/MySQL配置 (仅当type为postgresql或mysql时使用)
  host: "localhost"
  port: 5432
  username: "pams_user"
  password: "your_password"
  database: "pams"

# 安全配置
security:
  secret_key: "your-secret-key-here"
  jwt_secret_key: "your-jwt-secret-key"
  password_min_length: 8
  session_timeout: 24  # 小时

# 文件存储配置
storage:
  upload_folder: "data/uploads"
  genome_folder: "data/genomes"
  results_folder: "data/results"
  max_file_size: 16  # MB
  allowed_extensions: [".fasta", ".fa", ".fna", ".gbk", ".gb"]

# 分析工具配置
analysis:
  # 并行任务数量
  max_parallel_tasks: 4
  # 临时目录
  temp_directory: "data/tmp"
  
  # 工具路径配置
  tools:
    prokka: "/usr/local/bin/prokka"
    mlst: "/usr/local/bin/mlst"
    abricate: "/usr/local/bin/abricate"
    snippy: "/usr/local/bin/snippy"
    gubbins: "/usr/local/bin/run_gubbins.py"
    
  # 数据库路径
  databases:
    mlst: "/usr/local/db/mlst"
    abricate: "/usr/local/db/abricate"
    prokka: "/usr/local/db/prokka"

# 日志配置
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "logs/pams.log"
  max_size: 10  # MB
  backup_count: 5

# 用户界面配置
ui:
  default_language: "zh-CN"
  items_per_page: 20
  chart_colors: ["#409EFF", "#67C23A", "#E6A23C", "#F56C6C", "#909399"]

# 通知配置
notifications:
  email_enabled: false
  smtp_server: "localhost"
  smtp_port: 587
  smtp_username: ""
  smtp_password: ""
  from_email: "noreply@pams.local" 